server:
  port: 8003

spring:
  application:
    name: user-server #服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动包
    url: jdbc:mysql://localhost:3306/monitor_sys?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: cht021125
  devtools:
    restart:
      enabled: true #是否支持热部署cloud:
  cloud:
    nacos:
      discovery: #启用 spring cloud nacos discovery
        server-addr: 192.168.92.128:8848
  data:
    redis:
      host: 192.168.92.128
      port: 6379
      timeout: 1800000
      password: cht021125


mybatis-plus:
  type-aliases-package: com.neu.monitorSys.user.entity
  configuration:
    call-setters-on-nulls: false
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    banner: true
    db-config:
#      id-type: assign_uuid
      logic-delete-value: 0
      logic-not-delete-value: 1