server:
  port: 8004
spring:
  application:
    name: role-server
  devtools:
    restart:
      enabled: true #是否支持热部署cloud:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery: #启用 spring cloud nacos discovery
        server-addr: 192.168.244.128:8848
      config:
        server-addr: 192.168.244.128:8848
  config:
    import: nacos:database.yaml, nacos:redis.yaml,nacos:seata.yaml



# Mybatis log plugin 插件输出日志配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#  data:
#    redis:
#      host: 192.168.92.128
#      port: 6379
#      timeout: 1800000
#      password: cht021125

# application.yml
permissions:
  dependencies:
    "GET /api/v1/feedbacks/waiting-list":
      - GET /api/v1/grid-managers/available
    "GET /api/v1/grid-managers/available":
      - GET /api/v1/feedbacks/waiting-list
    "PUT /api/v1/roles/users/*/roles":
      - GET /api/v1/roles
    "GET /api/v1/permissions/tree":
      - GET /api/v1/permissions/role/*
    "GET /api/v1/permissions/role/*":
      - GET /api/v1/permissions/tree
    "POST /api/v1/feedbacks/assign":
      - GET /api/v1/feedbacks/search
      - GET /api/v1/grid-managers/search
