server:
  port: 8002
  compression:
    enabled: true
    mime-types: application/json, application/xml, text/html, text/xml, text/plain
    min-response-size: 1024

auth:
  white-list:
    - /api/v1/auth/login #密码登录
    - /api/v1/auth/login/mobile  #手机验证码登录
    - /api/v1/auth/public/register  #注册
    - /api/v1/code/sms #获取短信验证码
    - /api/v1/auth/normal/register #普通注册
    - /api/v1/auth/password/change #修改密码
    - /api/v1/auth/pwd/reset #重置密码
    - /api/v1/notification/feedback/connect
    - /api/v1/auth/logout #退出登录
    - /api/v1/notification/logout/connect #退出登录sse连接
    - /api/v1/notification/logout/close #关闭sse连接
    - /api/v1/notification/feedback/close #关闭sse连接
#    - /auth/verify
#    - /auth/refresh
spring:
  application:
    name: gateway

  #  data:
  #    redis:
  #      host: 192.168.92.128
  #      port: 6379
  #      timeout: 1800000
  #      password: cht021125
  main:
    web-application-type: reactive
  config:
    import: nacos:database.yaml, nacos:rabbitmq.yaml, nacos:redis.yaml,nacos:seata.yaml
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery: #启用 spring cloud nacos discovery
        server-addr: 192.168.244.128:8848
      config:
        server-addr: 192.168.244.128:8848
    gateway:
      httpclient:
        pool:
          max-connections: 1000
          acquire-timeout: 5000
      discovery:
        locator:
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "null"
            allowedMethods:
              - "*"
#              - GET
#              - POST
#              - PUT
#              - PATCH
#              - DELETE
#              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 360000
      routes:
        - id: auth
          uri: lb://auth-server
          predicates:
            - Path=/api/v1/auth/**,/api/v1/code/**
        - id: feedback
          uri: lb://feedback-server
          predicates:
            - Path=/api/v1/feedbacks/**
        - id: user
          uri: lb://user-server
          predicates:
            - Path=/api/v1/members/**,/api/v1/grid-managers/**
        - id: statistics
          uri: lb://statistics-server
          predicates:
            - Path=/api/v1/statistics/**
        - id: aqi
          uri: lb://aqi-server
          predicates:
            - Path=/api/v1/aqi/**
        - id: roles
          uri: lb://role-server
          predicates:
            - Path=/api/v1/roles/**,/api/v1/permissions/**
        - id: notice
          uri: lb://notification-server
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - RemoveResponseHeader=Transfer-Encoding
            - RewriteResponseHeader=Connection,(.*),keep-alive
            - RewriteResponseHeader=Cache-Control,(.*),no-cache
            - DedupeResponseHeader=Connection RETAIN_FIRST
            - name: AddResponseHeader
              args:
                name: X-Accel-Buffering
                value: "no"
logging:
  level:
    org.springframework.cloud.gateway: DEBUG






